version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    restart: always
